name: check-npm-install
on:
  pull_request:
    branches:
      - "main"
      - "master"
  workflow_dispatch:
  
jobs:
  call-check-npm-install:
    uses: yanoshi-1009/github-actions/.github/workflows/check-npm-install.yml@main
